2025-04-10 16:37:08,641 - cwan - ERROR - Exception on /login [GET]
Traceback (most recent call last):
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\cwan_project_demo\sample_project\cwanext\sample_project\sample_project.py", line 93, in login
    return render_template("Login.html", signin_template=signin_template, error_message=None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\cwan_project_demo\sample_project\cwanext\sample_project\templates\Login.html", line 4, in top-level template code
    <meta charset="{{ signin_template.head.meta_charset }}">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'None' has no attribute 'head'
2025-04-10 16:37:17,879 - cwan - ERROR - Exception on /login [GET]
Traceback (most recent call last):
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\cwan_project_demo\sample_project\cwanext\sample_project\sample_project.py", line 93, in login
    return render_template("Login.html", signin_template=signin_template, error_message=None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\cwan_project_demo\sample_project\cwanext\sample_project\templates\Login.html", line 4, in top-level template code
    <meta charset="{{ signin_template.head.meta_charset }}">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'None' has no attribute 'head'
2025-04-10 16:38:36,374 - cwan - INFO - Logging setup complete
2025-04-10 16:38:36,376 - cwan - INFO - Loading extensions: ['sample_project']
2025-04-10 16:38:37,211 - cwan - INFO - Loaded extension cwanext.sample_project
2025-04-10 16:55:55,130 - cwan - INFO - Logging setup complete
2025-04-10 16:55:55,131 - cwan - INFO - Loading extensions: ['sample_project']
2025-04-10 16:55:55,749 - cwan - ERROR - Failed to load extension cwanext.sample_project: cannot import name 'signin' from 'cwanext.sample_project.config.config' (C:\cwan_project_demo\sample_project\cwanext\sample_project\config\config.py)
2025-04-10 16:56:43,570 - cwan - INFO - Logging setup complete
2025-04-10 16:56:43,571 - cwan - INFO - Loading extensions: ['sample_project']
2025-04-10 16:56:44,105 - cwan - ERROR - Failed to load extension cwanext.sample_project: cannot import name 'signin' from 'cwanext.sample_project.config.config' (C:\cwan_project_demo\sample_project\cwanext\sample_project\config\config.py)
2025-04-10 16:57:40,604 - cwan - INFO - Logging setup complete
2025-04-10 16:57:40,605 - cwan - INFO - Loading extensions: ['sample_project']
2025-04-10 16:57:41,774 - cwan - INFO - Loaded extension cwanext.sample_project
2025-04-10 17:13:22,983 - cwan - INFO - Logging setup complete
2025-04-10 17:13:22,984 - cwan - INFO - Loading extensions: ['sample_project']
2025-04-10 17:13:24,114 - cwan - INFO - Loaded extension cwanext.sample_project
2025-04-10 17:47:32,021 - cwan - INFO - Logging setup complete
2025-04-10 17:47:32,022 - cwan - INFO - Loading extensions: ['sample_project']
2025-04-10 17:47:32,949 - cwan - INFO - Loaded extension cwanext.sample_project
